## Student Attendance Analytics with Pandas

In [1]:
import pandas as pd
import numpy as np

#### Section 0: Data Loading

In [2]:
df = pd.read_excel("CSEB_Attendance.xlsx")
df

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24CS061,KAVYA KAMATH,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
1,4MW24CS062,KEERTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
2,4MW24CS063,KEERTHI.R.SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
3,4MW24CS064,KHUSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
4,4MW24CS065,KISHAN KUMAR K,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS121,SAHANA M,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,83%,Warning,✓ Met,2026-10-09,0
61,4MW24CS122,SAKSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
62,4MW25CS404,MANISH M BHANDARY,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
63,4MW25CS405,MANYA PRARTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0%,Critical,36 more,Never,12
64,4MW25CS406,ROHAN,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,83%,Warning,✓ Met,2026-10-09,0

#### Section 1: Data Inspection

In [3]:
"""Q1. Display the first 10 rows, the shape of the DataFrame, and the data types of each column."""
#-----------------------------Write Solution Code-----------------------------
df.shape
df.head(10)
df.dtypes

Roll No                   str
Student Name              str
Subject                   str
Total Classes           int64
Present                 int64
Absent                  int64
Excused                 int64
Attendance %              str
Status                    str
Classes Needed (75%)      str
Last Present Date         str
Consecutive Absences    int64
dtype: object

In [4]:
"""Q2. Check for missing values in each column. Identify which columns have null values (especially Last Present Date with "Never") and report the count. """
#-----------------------------Write Solution Code-----------------------------
df.isnull()
df.isnull().sum()

Roll No                 0
Student Name            0
Subject                 0
Total Classes           0
Present                 0
Absent                  0
Excused                 0
Attendance %            0
Status                  0
Classes Needed (75%)    0
Last Present Date       0
Consecutive Absences    0
dtype: int64

In [8]:
"""Q3. Rename the columns to snake_case (e.g., Roll No → roll_no, Student Name → student_name, Attendance % → attendance_pct). Display the updated column list."""
#-----------------------------Write Solution Code-----------------------------
df.rename(columns={"Roll No":"roll_no"},inplace=True)
df.rename(columns={"Student Name":"student_name"},inplace=True)
df.rename(columns={"Attendance %":"attendance_pct"},inplace=True)
df

,roll_no,student_name,Subject,Total Classes,Present,Absent,Excused,attendance_pct,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24CS061,KAVYA KAMATH,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
1,4MW24CS062,KEERTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
2,4MW24CS063,KEERTHI.R.SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
3,4MW24CS064,KHUSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
4,4MW24CS065,KISHAN KUMAR K,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS121,SAHANA M,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,83%,Warning,✓ Met,2026-10-09,0
61,4MW24CS122,SAKSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
62,4MW25CS404,MANISH M BHANDARY,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
63,4MW25CS405,MANYA PRARTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0%,Critical,36 more,Never,12
64,4MW25CS406,ROHAN,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,83%,Warning,✓ Met,2026-10-09,0

In [9]:
"""Q4. Convert Attendance % from string format (e.g., "64%") to a numeric float column (0.64 or 64.0). Also convert Last Present Date to datetime, handling "Never" as NaT."""
#-----------------------------Write Solution Code-----------------------------


df["attendance_pct"] = (
    df["attendance_pct"]
    .astype("string")
    .str.replace("%", "", regex=False)
    .astype(float) / 100
)

df["Last Present Date"] = pd.to_datetime(
    df["Last Present Date"].replace("Never", pd.NaT),
    errors="coerce"
)

print(df.head())

      roll_no      student_name                                  Subject  \
0  4MW24CS061      KAVYA KAMATH  Data Science & GenAI - 3nd Yr - CSE - B
1  4MW24CS062         KEERTHANA  Data Science & GenAI - 3nd Yr - CSE - B
2  4MW24CS063  KEERTHI.R.SHETTY  Data Science & GenAI - 3nd Yr - CSE - B
3  4MW24CS064            KHUSHI  Data Science & GenAI - 3nd Yr - CSE - B
4  4MW24CS065    KISHAN KUMAR K  Data Science & GenAI - 3nd Yr - CSE - B

   Total Classes  Present  Absent  Excused  attendance_pct Status  \
0             12       12       0        0            1.00   Safe
1             12       12       0        0            1.00   Safe
2             12       12       0        0            1.00   Safe
3             12       11       1        0            0.92   Safe
4             12       11       1        0            0.92   Safe

  Classes Needed (75%) Last Present Date  Consecutive Absences
0                ✓ Met        2026-10-09                     0
1                ✓ Met        2026-10-09                     0
2                ✓ Met        2026-10-09                     0
3                ✓ Met        2026-10-09                     0
4                ✓ Met        2026-10-09                     0

#### Section 2: Filtering & Selection

In [10]:
"""Q5. Filter and display all students whose Status is "Critical". Sort them by Attendance % in ascending order."""
#-----------------------------Write Solution Code-----------------------------
critical_students = df[df["Status"] == "Critical"]

critical_students = critical_students.sort_values(
    by="attendance_pct",
    ascending=True
)

display(critical_students)

,roll_no,student_name,Subject,Total Classes,Present,Absent,Excused,attendance_pct,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
10,4MW24CS071,LAXMEESH V,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0.00,Critical,36 more,NaT,12
63,4MW25CS405,MANYA PRARTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0.00,Critical,36 more,NaT,12
13,4MW24CS074,MAHALINGAPPA C,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-22,4
5,4MW24CS066,KOUSHTUBHA,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-18,5
49,4MW24CS110,PRATHWEESH,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-18,5
46,4MW24CS107,PRATHAM G KUMAR,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-18,5
35,4MW24CS096,NITHIL SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,1,11,0,0.08,Critical,32 more,2026-09-18,5
29,4MW24CS090,NIKHIL NAIK,Data Science & GenAI - 3nd Yr - CSE - B,12,7,5,0,0.58,Critical,8 more,2026-10-09,0
51,4MW24CS112,RAHUL,Data Science & GenAI - 3nd Yr - CSE - B,12,7,5,0,0.58,Critical,8 more,2026-09-29,2

In [8]:
"""Q6. Extract all students who have 0 present days (fully absent). List their roll numbers, names, and consecutive absences."""
#-----------------------------Write Solution Code-----------------------------
absent_students = df[df["Present"]==0]
result = absent_students[
    ["roll_no", "student_name", "Consecutive Absences"]
]

display(result)

       roll_no     student_name  Consecutive Absences
10  4MW24CS071       LAXMEESH V                    12
63  4MW25CS405  MANYA PRARTHANA                    12

In [11]:
"""Q7. Using .loc and .iloc, display:
(a) All "Safe" students using .loc
(b) The first 15 rows and columns 2-6 using .iloc """
#-----------------------------Write Solution Code-----------------------------
safe=df.loc[df["Status"]=="Safe"]
print(df.iloc[:15,1:6])

             student_name                                  Subject  \
0            KAVYA KAMATH  Data Science & GenAI - 3nd Yr - CSE - B
1               KEERTHANA  Data Science & GenAI - 3nd Yr - CSE - B
2        KEERTHI.R.SHETTY  Data Science & GenAI - 3nd Yr - CSE - B
3                  KHUSHI  Data Science & GenAI - 3nd Yr - CSE - B
4          KISHAN KUMAR K  Data Science & GenAI - 3nd Yr - CSE - B
5              KOUSHTUBHA  Data Science & GenAI - 3nd Yr - CSE - B
6                  KRITHI  Data Science & GenAI - 3nd Yr - CSE - B
7                KRITHIKA  Data Science & GenAI - 3nd Yr - CSE - B
8                 LAKSHMI  Data Science & GenAI - 3nd Yr - CSE - B
9   LAVANYA SHANKAR MOGER  Data Science & GenAI - 3nd Yr - CSE - B
10             LAXMEESH V  Data Science & GenAI - 3nd Yr - CSE - B
11              LIKHITA S  Data Science & GenAI - 3nd Yr - CSE - B
12           LIPIKA NAYAK  Data Science & GenAI - 3nd Yr - CSE - B
13         MAHALINGAPPA C  Data Science & GenAI - 3nd Yr - CSE - B
14         MANASA R KULAL  Data Science & GenAI - 3nd Yr - CSE - B

    Total Classes  Present  Absent
0              12       12       0
1              12       12       0
2              12       12       0
3              12       11       1
4              12       11       1
5              12        1      11
6              12       12       0
7              12       12       0
8              12       12       0
9              12       10       2
10             12        0      12
11             12       12       0
12             12       11       1
13             12        1      11
14             12       12       0

In [12]:
"""Q8. Find all students whose Consecutive Absences is greater than or equal to 5. Display their name, status, and last present date."""
#-----------------------------Write Solution Code-----------------------------

cons_absentees=df[df["Consecutive Absences"]>=5]
result=cons_absentees[["student_name","Status","Last Present Date"]]
print(result)

       student_name    Status Last Present Date
5        KOUSHTUBHA  Critical        2026-09-18
10       LAXMEESH V  Critical               NaT
35    NITHIL SHETTY  Critical        2026-09-18
46  PRATHAM G KUMAR  Critical        2026-09-18
49       PRATHWEESH  Critical        2026-09-18
63  MANYA PRARTHANA  Critical               NaT

### Section 3: Grouping & Aggregation

In [13]:
"""Q9. Group the data by Status and compute: 
a) Count of students 
b) Average attendance %  
c) Maximum consecutive absences"""
#-----------------------------Write Solution Code-----------------------------
result = df.groupby("Status").agg(
    Student_Count=("roll_no", "count"),
    Average_Attendance=("attendance_pct", "mean"),
    Max_Consecutive_Absences=("Consecutive Absences", "max")
)

display(result)

          Student_Count  Average_Attendance  Max_Consecutive_Absences
Status
Critical              9            0.173333                        12
Safe                 42            0.969524                         0
Warning              14            0.807143                         1

In [14]:
"""Q10. Create a new column Attendance Category:
≥ 90% → "Excellent"
75-89% → "Good"
60-74% → "Average"
< 60% → "Poor"
Then use groupby() to count students in each category."""
#-----------------------------Write Solution Code-----------------------------

attendance = df["attendance_pct"] * 100


df["Attendance Category"] = pd.cut(
    attendance,
    bins=[-float("inf"), 60, 75, 90, float("inf")],
    labels=["Poor", "Average", "Good", "Excellent"],
    right=False
)


result = df.groupby("Attendance Category", observed=False).size().reset_index(name="Student Count")

display(result)

  Attendance Category  Student Count
0                Poor              9
1             Average              0
2                Good             14
3           Excellent             42

In [15]:
"""Q11. Calculate the total number of classes conducted (sum of Total Classes) and the total present/absent counts across all students using .agg()."""
#-----------------------------Write Solution Code-----------------------------

result = df[["Total Classes", "Present", "Absent"]].agg("sum")
display(result)

Total Classes    780
Present          643
Absent           137
dtype: int64

In [16]:
"""Q12. Group by Status and use .agg() to find:
a)min, max, and mean of Present
b)sum of Absent"""
#-----------------------------Write Solution Code-----------------------------
group=df.groupby("Status")["Present"].agg(["min","max","mean"])
absent=df["Absent"].agg(["sum"])
print(absent)
print(group)

sum    137
Name: Absent, dtype: int64
          min  max       mean
Status
Critical    0    7   2.111111
Safe       11   12  11.619048
Warning     9   10   9.714286

### Section 4: Feature Engineering & Transformation

In [17]:
"""Q13. Create a new column Risk Score using the formula:
Risk Score = (Absent * 0.4) + (Consecutive Absences * 0.6)
Display the top 10 students with the highest risk score."""
#-----------------------------Write Solution Code-----------------------------

df["Risk Score"] = (
    (df["Absent"] * 0.4) +
    (df["Consecutive Absences"] * 0.6)
)

top_10_risk = df.sort_values(
    by="Risk Score",
    ascending=False
).head(10)

display(top_10_risk[
    ["roll_no", "student_name", "Absent",
     "Consecutive Absences", "Risk Score"]
])

       roll_no     student_name  Absent  Consecutive Absences  Risk Score
10  4MW24CS071       LAXMEESH V      12                    12        12.0
63  4MW25CS405  MANYA PRARTHANA      12                    12        12.0
46  4MW24CS107  PRATHAM G KUMAR      11                     5         7.4
35  4MW24CS096    NITHIL SHETTY      11                     5         7.4
5   4MW24CS066       KOUSHTUBHA      11                     5         7.4
49  4MW24CS110       PRATHWEESH      11                     5         7.4
13  4MW24CS074   MAHALINGAPPA C      11                     4         6.8
51  4MW24CS112            RAHUL       5                     2         3.2
29  4MW24CS090      NIKHIL NAIK       5                     0         2.0
33  4MW24CS094        NISHA M B       2                     1         1.4

In [18]:
"""Q14. Add a column Classes Needed (Numeric) by extracting the numeric value from the Classes Needed (75%) column (e.g., "5 more" → 5, "✓ Met" → 0)."""
#-----------------------------Write Solution Code-----------------------------

df["Classes Needed (Numeric)"] = (
    df["Classes Needed (75%)"]
    .str.extract(r"(\d+)", expand=False)
    .fillna("0")
    .astype(int)
)

display(df[["Classes Needed (75%)", "Classes Needed (Numeric)"]])

   Classes Needed (75%)  Classes Needed (Numeric)
0                 ✓ Met                         0
1                 ✓ Met                         0
2                 ✓ Met                         0
3                 ✓ Met                         0
4                 ✓ Met                         0
..                  ...                       ...
60                ✓ Met                         0
61                ✓ Met                         0
62                ✓ Met                         0
63              36 more                        36
64                ✓ Met                         0

[65 rows x 2 columns]

In [19]:
"""Q15. Using apply() with a lambda function, create a column Attendance Flag that returns:
a)"Defaulter" if attendance < 75%
b)"Safe" otherwise """
#-----------------------------Write Solution Code-----------------------------
df["Attendance Flag"] = df["attendance_pct"].apply(
    lambda x: "Defaulter" if x < 0.75 else "Safe"
)

display(df[["student_name", "attendance_pct", "Attendance Flag"]])

         student_name  attendance_pct Attendance Flag
0        KAVYA KAMATH            1.00            Safe
1           KEERTHANA            1.00            Safe
2    KEERTHI.R.SHETTY            1.00            Safe
3              KHUSHI            0.92            Safe
4      KISHAN KUMAR K            0.92            Safe
..                ...             ...             ...
60           SAHANA M            0.83            Safe
61             SAKSHI            0.92            Safe
62  MANISH M BHANDARY            0.92            Safe
63    MANYA PRARTHANA            0.00       Defaulter
64              ROHAN            0.83            Safe

[65 rows x 3 columns]

In [20]:
"""Q16. Use pd.cut() to bin students into attendance ranges: [0-50, 50-75, 75-90, 90-100] and label them as ["Critical", "Warning", "Good", "Excellent"]."""
#-----------------------------Write Solution Code-----------------------------


attendance = df["attendance_pct"] * 100


df["Attendance Range"] = pd.cut(
    attendance,
    bins=[0, 50, 75, 90, 100],
    labels=["Critical", "Warning", "Good", "Excellent"],
    include_lowest=True
)

display(df[["student_name", "attendance_pct", "Attendance Range"]])

         student_name  attendance_pct Attendance Range
0        KAVYA KAMATH            1.00        Excellent
1           KEERTHANA            1.00        Excellent
2    KEERTHI.R.SHETTY            1.00        Excellent
3              KHUSHI            0.92        Excellent
4      KISHAN KUMAR K            0.92        Excellent
..                ...             ...              ...
60           SAHANA M            0.83             Good
61             SAKSHI            0.92        Excellent
62  MANISH M BHANDARY            0.92        Excellent
63    MANYA PRARTHANA            0.00         Critical
64              ROHAN            0.83             Good

[65 rows x 3 columns]

### Section 5: Advanced Analysis

In [21]:
"""Q17. Using pivot_table(), create a summary showing the count of students by Status and Attendance Category (created in Q10)."""
#-----------------------------Write Solution Code-----------------------------

pivot = pd.pivot_table(
    df,
    index="Status",
    columns="Attendance Category",
    values="roll_no",
    aggfunc="count",
    fill_value=0,
    observed=False
)

display(pivot)

Attendance Category  Poor  Average  Good  Excellent
Status
Critical                9        0     0          0
Safe                    0        0     0         42
Warning                 0        0    14          0

In [22]:
"""Q18. Identify duplicate student names (e.g., "ANANYA", "DISHA") and display all rows where the base name repeats. Use string manipulation to extract the base name."""
#-----------------------------Write Solution Code-----------------------------

df["Base Name"] = (
    df["student_name"]
    .str.strip()
    .str.upper()
    .str.replace(r"\s*\d+$", "", regex=True)
)


duplicate_names = df["Base Name"].duplicated(keep=False)


result = df.loc[duplicate_names].sort_values("Base Name")

display(result)

Empty DataFrame
Columns: [roll_no, student_name, Subject, Total Classes, Present, Absent, Excused, attendance_pct, Status, Classes Needed (75%), Last Present Date, Consecutive Absences, Attendance Category, Risk Score, Classes Needed (Numeric), Attendance Flag, Attendance Range, Base Name]
Index: []

In [23]:
""""Q19. Merge this dataset with a hypothetical Student_Details DataFrame containing Roll No, Branch, and Semester. Perform an inner join and display the merged result."""
#-----------------------------Write Solution Code-----------------------------

Student_Details = pd.DataFrame({
    "roll_no": df["roll_no"].unique(),
    "Branch": ["CSE"] * df["roll_no"].nunique(),
    "Semester": [5] * df["roll_no"].nunique()
})

merged_df = pd.merge(
    df,
    Student_Details,
    on="roll_no",
    how="inner"
)

display(merged_df)

,roll_no,student_name,Subject,Total Classes,Present,Absent,Excused,attendance_pct,Status,Classes Needed (75%),Last Present Date,Consecutive Absences,Attendance Category,Risk Score,Classes Needed (Numeric),Attendance Flag,Attendance Range,Base Name,Branch,Semester
0,4MW24CS061,KAVYA KAMATH,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,1.00,Safe,✓ Met,2026-10-09,0,Excellent,0.0,0,Safe,Excellent,KAVYA KAMATH,CSE,5
1,4MW24CS062,KEERTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,1.00,Safe,✓ Met,2026-10-09,0,Excellent,0.0,0,Safe,Excellent,KEERTHANA,CSE,5
2,4MW24CS063,KEERTHI.R.SHETTY,Data Science & GenAI - 3nd Yr - CSE - B,12,12,0,0,1.00,Safe,✓ Met,2026-10-09,0,Excellent,0.0,0,Safe,Excellent,KEERTHI.R.SHETTY,CSE,5
3,4MW24CS064,KHUSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,Excellent,0.4,0,Safe,Excellent,KHUSHI,CSE,5
4,4MW24CS065,KISHAN KUMAR K,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,Excellent,0.4,0,Safe,Excellent,KISHAN KUMAR K,CSE,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS121,SAHANA M,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,0.83,Warning,✓ Met,2026-10-09,0,Good,0.8,0,Safe,Good,SAHANA M,CSE,5
61,4MW24CS122,SAKSHI,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,Excellent,0.4,0,Safe,Excellent,SAKSHI,CSE,5
62,4MW25CS404,MANISH M BHANDARY,Data Science & GenAI - 3nd Yr - CSE - B,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,0,Excellent,0.4,0,Safe,Excellent,MANISH M BHANDARY,CSE,5
63,4MW25CS405,MANYA PRARTHANA,Data Science & GenAI - 3nd Yr - CSE - B,12,0,12,0,0.00,Critical,36 more,NaT,12,Poor,12.0,36,Defaulter,Critical,MANYA PRARTHANA,CSE,5
64,4MW25CS406,ROHAN,Data Science & GenAI - 3nd Yr - CSE - B,12,10,2,0,0.83,Warning,✓ Met,2026-10-09,0,Good,0.8,0,Safe,Good,ROHAN,CSE,5

In [24]:
"""Q20. Export the following to separate CSV files:
(a) All "Critical" students
(b) Summary statistics grouped by Status
(c) Top 10 students by Risk Score"""
#-----------------------------Write Solution Code-----------------------------


critical_students = df[df["Status"] == "Critical"]
critical_students.to_csv("Critical_Students.csv", index=False)


status_summary = df.groupby("Status").agg(
    Student_Count=("roll_no", "count"),
    Average_Attendance=("attendance_pct", "mean"),
    Max_Consecutive_Absences=("Consecutive Absences", "max")
).reset_index()

status_summary.to_csv("Status_Summary.csv", index=False)


top_10_risk = df.sort_values(
    by="Risk Score",
    ascending=False
).head(10)

top_10_risk.to_csv("Top_10_Risk_Score.csv", index=False)

print("All three CSV files exported successfully!")

All three CSV files exported successfully!