Column Transformation in pandas

In [1]:
import pandas as pd

Rows&Col - selections

In [5]:
sdata=pd.read_csv("subdata_pandas/student1.csv")
sdata

    id firstName  lastName  age  marks   fees
0  101    Akshay    Shetty   20     85  25000
1  102    Ananya       Rao   21     92  30000
2  103     Rohit  Bhandary   19     76  28000
3  104     Nisha   D'Souza   20     88  25000
4  105   Karthik   Poojary   22     69  32000
5  106    Shreya    Shetty   19     95  30000
6  107     Rohan      Naik   21     72  27000
7  108   Deepika      Bhat   20     81  28000
8  109  Abhishek    Kotian   22     64  26000
9  110     Pooja       Rai   19     90  30000

In [10]:
#To select columns
sdata[['firstName','fees','age']]
# To select details of karthik
sdata.loc[sdata.firstName=="Karthik"]
sdata.loc[sdata.fees>=30000]
#to slicing on rows
sdata.loc[1:7]
# to slicing on rows & columns
sdata.iloc[:4,:3]
sdata.iloc[2:7,1:4]

  firstName  lastName  age
2     Rohit  Bhandary   19
3     Nisha   D'Souza   20
4   Karthik   Poojary   22
5    Shreya    Shetty   19
6     Rohan      Naik   21

Filter

In [11]:
sdata=pd.read_csv("subdata_pandas/student1.csv")
sdata

    id firstName  lastName  age  marks   fees
0  101    Akshay    Shetty   20     85  25000
1  102    Ananya       Rao   21     92  30000
2  103     Rohit  Bhandary   19     76  28000
3  104     Nisha   D'Souza   20     88  25000
4  105   Karthik   Poojary   22     69  32000
5  106    Shreya    Shetty   19     95  30000
6  107     Rohan      Naik   21     72  27000
7  108   Deepika      Bhat   20     81  28000
8  109  Abhishek    Kotian   22     64  26000
9  110     Pooja       Rai   19     90  30000

In [12]:
sdata['age']>20
sdata[sdata['age']>20]
student_age_filter=sdata[sdata['age']>20]
student_age_filter

    id firstName lastName  age  marks   fees
1  102    Ananya      Rao   21     92  30000
4  105   Karthik  Poojary   22     69  32000
6  107     Rohan     Naik   21     72  27000
8  109  Abhishek   Kotian   22     64  26000

In [15]:
sdata.where(sdata['age']>20)
sdata.where(sdata['age']>20,other="Minor")

      id firstName lastName    age  marks   fees
0  Minor     Minor    Minor  Minor  Minor  Minor
1    102    Ananya      Rao     21     92  30000
2  Minor     Minor    Minor  Minor  Minor  Minor
3  Minor     Minor    Minor  Minor  Minor  Minor
4    105   Karthik  Poojary     22     69  32000
5  Minor     Minor    Minor  Minor  Minor  Minor
6    107     Rohan     Naik     21     72  27000
7  Minor     Minor    Minor  Minor  Minor  Minor
8    109  Abhishek   Kotian     22     64  26000
9  Minor     Minor    Minor  Minor  Minor  Minor

In [19]:
sdata.loc[(sdata['marks']>=85,"result")]="selected"
sdata.loc[(sdata['marks']<85,"result")]="not selected"
sdata

    id firstName  lastName  age  marks   fees        result
0  101    Akshay    Shetty   20     85  25000      selected
1  102    Ananya       Rao   21     92  30000      selected
2  103     Rohit  Bhandary   19     76  28000  not selected
3  104     Nisha   D'Souza   20     88  25000      selected
4  105   Karthik   Poojary   22     69  32000  not selected
5  106    Shreya    Shetty   19     95  30000      selected
6  107     Rohan      Naik   21     72  27000  not selected
7  108   Deepika      Bhat   20     81  28000  not selected
8  109  Abhishek    Kotian   22     64  26000  not selected
9  110     Pooja       Rai   19     90  30000      selected

In [20]:
sdata["FullName"]=sdata['firstName']+" "+sdata["lastName"]
sdata

    id firstName  lastName  age  marks   fees        result         FullName
0  101    Akshay    Shetty   20     85  25000      selected    Akshay Shetty
1  102    Ananya       Rao   21     92  30000      selected       Ananya Rao
2  103     Rohit  Bhandary   19     76  28000  not selected   Rohit Bhandary
3  104     Nisha   D'Souza   20     88  25000      selected    Nisha D'Souza
4  105   Karthik   Poojary   22     69  32000  not selected  Karthik Poojary
5  106    Shreya    Shetty   19     95  30000      selected    Shreya Shetty
6  107     Rohan      Naik   21     72  27000  not selected       Rohan Naik
7  108   Deepika      Bhat   20     81  28000  not selected     Deepika Bhat
8  109  Abhishek    Kotian   22     64  26000  not selected  Abhishek Kotian
9  110     Pooja       Rai   19     90  30000      selected        Pooja Rai