Dealing with Duplicate values,Missing Data

In [17]:
import pandas as pd
import numpy as np

Duplicate Values

In [4]:
cdata=pd.read_csv("subdata_pandas/company.csv")
cdata

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0

In [9]:
#overall duplicate
cdata.duplicated()#boolean
cdata[cdata.duplicated()]
#Based on
cdata['EEID'].duplicated()#boolean
cdata[cdata['EEID'].duplicated()]

cdata.drop_duplicates()
cdata['EEID'].drop_duplicates()

0    EMP01
1    EMP02
2    EMP03
4    EMP05
5    EMP06
Name: EEID, dtype: str

In [13]:

#check null values
cdata.isnull()
edata=pd.read_csv("subdata_pandas/employee.csv")
edata.isnull().sum()
cdata.isnull().sum()

EEID      0
Name      1
gender    1
salary    2
dtype: int64

In [15]:
cdata['salary'].isnull().sum()

np.int64(2)

In [16]:
#Elementate nan rows
cdata.dropna()

    EEID    Name gender   salary
1  EMP02   rohit      M  25000.0
3  EMP01  ayushi      F  20000.0
6  EMP02   rohit      M  25000.0

In [24]:
#Replace NaN with any value
cdata.replace(np.nan,"Insufficient")
#Replace NaN with 30000 in salary
cdata['salary']=cdata['salary'].replace(np.nan, 30000)
#replace Nan salary with avg
mean=np.mean(cdata['salary'])
#M1
#cdata['salary'].replace(np)
#cdata['salary']=cdata['salary'].replace(np.nan,mean)
#cdata
#M2
cdata['salary']=cdata['salary'].fillna(mean)
cdata

    EEID      Name gender   salary
0  EMP01    ayushi      F  30000.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M  30000.0
6  EMP02     rohit      M  25000.0

In [28]:
cdata=pd.read_csv("subdata_pandas/company.csv")
cdata

# forword Fill (prev row)
cdata.ffill()
#backword fill (next row)
cdata.bfill()
#save it

#cdata=['salary']=cdata['salary'].bfill()
#cdata

    EEID      Name gender   salary
0  EMP01    ayushi      F  25000.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali      F  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05     rohit      M  25000.0
5  EMP06     rohit      M  25000.0
6  EMP02     rohit      M  25000.0