Creation of Data Frames

In [1]:
import pandas as pd

DataFrames

In [2]:
student={
    'id':['CS080','CS117','CS116','CS105'],
    'name':['Mayur','Rohan','Rijesh','Pranav'],
    'age':[19,20,18,21]
}
#Creation of Dataframe
df=pd.DataFrame(student)
df

      id    name  age
0  CS080   Mayur   19
1  CS117   Rohan   20
2  CS116  Rijesh   18
3  CS105  Pranav   21

In [6]:
#Shape
df.shape
#size
df.size
#Columns
df.columns
#Rename
df.rename(columns={"id":"student_id"},inplace=True)
df

  student_id    name  age
0      CS080   Mayur   19
1      CS117   Rohan   20
2      CS116  Rijesh   18
3      CS105  Pranav   21